/*
 * Copyright 2017 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import org.joda.time.LocalDate
import jto.validation.Rule

package object models {

  type ValidationRule[A] = Rule[A,A]

  //ISO 4217 currency codes
  //http://www.iso.org/iso/home/standards/currency_codes.htm

  val currencies = Seq(
      "AED",
      "AFN",
      "ALL",
      "AMD",
      "ANG",
      "AOA",
      "ARS",
      "AUD",
      "AWG",
      "AZN",
      "BAM",
      "BBD",
      "BDT",
      "BGN",
      "BHD",
      "BIF",
      "BMD",
      "BND",
      "BOB",
      "BOV",
      "BRL",
      "BSD",
      "BTN",
      "BWP",
      "BYR",
      "BZD",
      "CAD",
      "CDF",
      "CHE",
      "CHF",
      "CHW",
      "CLF",
      "CLP",
      "CNY",
      "COP",
      "COU",
      "CRC",
      "CUC",
      "CUP",
      "CVE",
      "CZK",
      "DJF",
      "DKK",
      "DOP",
      "DZD",
      "EGP",
      "ERN",
      "ETB",
      "EUR",
      "FJD",
      "FKP",
      "GBP",
      "GEL",
      "GHS",
      "GIP",
      "GMD",
      "GNF",
      "GTQ",
      "GYD",
      "HKD",
      "HNL",
      "HRK",
      "HTG",
      "HUF",
      "IDR",
      "ILS",
      "INR",
      "IQD",
      "IRR",
      "ISK",
      "JMD",
      "JOD",
      "JPY",
      "KES",
      "KGS",
      "KHR",
      "KMF",
      "KPW",
      "KRW",
      "KWD",
      "KYD",
      "KZT",
      "LAK",
      "LBP",
      "LKR",
      "LRD",
      "LSL",
      "LYD",
      "MAD",
      "MDL",
      "MGA",
      "MKD",
      "MMK",
      "MNT",
      "MOP",
      "MRO",
      "MUR",
      "MVR",
      "MWK",
      "MXN",
      "MXV",
      "MYR",
      "MZN",
      "NAD",
      "NGN",
      "NIO",
      "NOK",
      "NPR",
      "NZD",
      "OMR",
      "PAB",
      "PEN",
      "PGK",
      "PHP",
      "PKR",
      "PLN",
      "PYG",
      "QAR",
      "RON",
      "RSD",
      "RUB",
      "RWF",
      "SAR",
      "SBD",
      "SCR",
      "SDG",
      "SEK",
      "SGD",
      "SHP",
      "SLL",
      "SOS",
      "SRD",
      "SSP",
      "STD",
      "SVC",
      "SYP",
      "SZL",
      "THB",
      "TJS",
      "TMT",
      "TND",
      "TOP",
      "TRY",
      "TTD",
      "TWD",
      "TZS",
      "UAH",
      "UGX",
      "USD",
      "USN",
      "UYI",
      "UYU",
      "UZS",
      "VEF",
      "VND",
      "VUV",
      "WST",
      "XAF",
      "XCD",
      "XDR",
      "XOF",
      "XPF",
      "XSU",
      "XUA",
      "YER",
      "ZAR",
      "ZMW",
      "ZWL"
  )

  val countries = Seq(
    Country("Afghanistan", "AF"),
    Country("Åland Islands", "AX"),
    Country("Albania", "AL"),
    Country("Algeria", "DZ"),
    Country("American Samoa", "AS"),
    Country("Andorra", "AD"),
    Country("Angola", "AO"),
    Country("Anguilla", "AI"),
    Country("Antarctica", "AQ"),
    Country("Antigua and Barbuda", "AG"),
    Country("Argentina", "AR"),
    Country("Armenia", "AM"),
    Country("Aruba", "AW"),
    Country("Australia", "AU"),
    Country("Austria", "AT"),
    Country("Azerbaijan", "AZ"),
    Country("Bahamas", "BS"),
    Country("Bahrain", "BH"),
    Country("Bangladesh", "BD"),
    Country("Barbados", "BB"),
    Country("Belarus", "BY"),
    Country("Belgium", "BE"),
    Country("Belize", "BZ"),
    Country("Benin", "BJ"),
    Country("Bermuda", "BM"),
    Country("Bhutan", "BT"),
    Country("Bolivia, Plurinational State of", "BO"),
    Country("Bonaire, Sint Eustatius and Saba", "BQ"),
    Country("Bosnia and Herzegovina", "BA"),
    Country("Botswana", "BW"),
    Country("Bouvet Island", "BV"),
    Country("Brazil", "BR"),
    Country("British Indian Ocean Territory", "IO"),
    Country("Brunei Darussalam", "BN"),
    Country("Bulgaria", "BG"),
    Country("Burkina Faso", "BF"),
    Country("Burundi", "BI"),
    Country("Cambodia", "KH"),
    Country("Cameroon", "CM"),
    Country("Canada", "CA"),
    Country("Cape Verde", "CV"),
    Country("Cayman Islands", "KY"),
    Country("Central African Republic", "CF"),
    Country("Chad", "TD"),
    Country("Chile", "CL"),
    Country("China", "CN"),
    Country("Christmas Island", "CX"),
    Country("Cocos (Keeling) Islands", "CC"),
    Country("Colombia", "CO"),
    Country("Comoros", "KM"),
    Country("Congo", "CG"),
    Country("Congo, the Democratic Republic of the", "CD"),
    Country("Cook Islands", "CK"),
    Country("Costa Rica", "CR"),
    Country("Côte d'Ivoire", "CI"),
    Country("Croatia", "HR"),
    Country("Cuba", "CU"),
    Country("Curaçao", "CW"),
    Country("Cyprus", "CY"),
    Country("Czech Republic", "CZ"),
    Country("Denmark", "DK"),
    Country("Djibouti", "DJ"),
    Country("Dominica", "DM"),
    Country("Dominican Republic", "DO"),
    Country("East Timor", "TP"),
    Country("Ecuador", "EC"),
    Country("Egypt", "EG"),
    Country("El Salvador", "SV"),
    Country("Equatorial Guinea", "GQ"),
    Country("Eritrea", "ER"),
    Country("Estonia", "EE"),
    Country("Ethiopia", "ET"),
    Country("European Union", "EU"),
    Country("Falkland Islands (Malvinas)", "FK"),
    Country("Faroe Islands", "FO"),
    Country("Fiji", "FJ"),
    Country("Finland", "FI"),
    Country("France", "FR"),
    Country("French Guiana", "GF"),
    Country("French Polynesia", "PF"),
    Country("French Southern Territories", "TF"),
    Country("Gabon", "GA"),
    Country("Gambia", "GM"),
    Country("Georgia", "GE"),
    Country("Germany", "DE"),
    Country("Ghana", "GH"),
    Country("Gibraltar", "GI"),
    Country("Greece", "GR"),
    Country("Greenland", "GL"),
    Country("Grenada", "GD"),
    Country("Guadeloupe", "GP"),
    Country("Guam", "GU"),
    Country("Guatemala", "GT"),
    Country("Guernsey", "GG"),
    Country("Guinea", "GN"),
    Country("Guinea-Bissau", "GW"),
    Country("Guyana", "GY"),
    Country("Haiti", "HT"),
    Country("Heard Island and McDonald Islands", "HM"),
    Country("Holy See (Vatican City State)", "VA"),
    Country("Honduras", "HN"),
    Country("Hong Kong", "HK"),
    Country("Hungary", "HU"),
    Country("Iceland", "IS"),
    Country("India", "IN"),
    Country("Indonesia", "ID"),
    Country("Iran, Islamic Republic of", "IR"),
    Country("Iraq", "IQ"),
    Country("Ireland", "IE"),
    Country("Isle of Man", "IM"),
    Country("Israel", "IL"),
    Country("Italy", "IT"),
    Country("Jamaica", "JM"),
    Country("Japan", "JP"),
    Country("Jersey", "JE"),
    Country("Jordan", "JO"),
    Country("Kazakhstan", "KZ"),
    Country("Kenya", "KE"),
    Country("Kiribati", "KI"),
    Country("Korea, Democratic People's Republic of", "KP"),
    Country("Korea, Republic of", "KR"),
    Country("Kuwait", "KW"),
    Country("Kyrgyzstan", "KG"),
    Country("Lao People's Democratic Republic", "LA"),
    Country("Latvia", "LV"),
    Country("Lebanon", "LB"),
    Country("Lesotho", "LS"),
    Country("Liberia", "LR"),
    Country("Libya", "LY"),
    Country("Liechtenstein", "LI"),
    Country("Lithuania", "LT"),
    Country("Luxembourg", "LU"),
    Country("Macao", "MO"),
    Country("Macedonia, the Former Yugoslav Republic of", "MK"),
    Country("Madagascar", "MG"),
    Country("Malawi", "MW"),
    Country("Malaysia", "MY"),
    Country("Maldives", "MV"),
    Country("Mali", "ML"),
    Country("Malta", "MT"),
    Country("Marshall Islands", "MH"),
    Country("Martinique", "MQ"),
    Country("Mauritania", "MR"),
    Country("Mauritius", "MU"),
    Country("Mayotte", "YT"),
    Country("Mexico", "MX"),
    Country("Micronesia, Federated States of", "FM"),
    Country("Moldova, Republic of", "MD"),
    Country("Monaco", "MC"),
    Country("Mongolia", "MN"),
    Country("Montenegro", "ME"),
    Country("Montserrat", "MS"),
    Country("Morocco", "MA"),
    Country("Mozambique", "MZ"),
    Country("Myanmar", "MM"),
    Country("Namibia", "NA"),
    Country("Nauru", "NR"),
    Country("Nepal", "NP"),
    Country("Netherlands", "NL"),
    Country("Netherlands Antilles", "AN"),
    Country("Neutral Zone", "NT"),
    Country("New Caledonia", "NC"),
    Country("New Zealand", "NZ"),
    Country("Nicaragua", "NI"),
    Country("Niger", "NE"),
    Country("Nigeria", "NG"),
    Country("Niue", "NU"),
    Country("Norfolk Island", "NF"),
    Country("Northern Mariana Islands", "MP"),
    Country("Norway", "NO"),
    Country("Oman", "OM"),
    Country("Pakistan", "PK"),
    Country("Palau", "PW"),
    Country("Palestine, State of", "PS"),
    Country("Panama", "PA"),
    Country("Papua New Guinea", "PG"),
    Country("Paraguay", "PY"),
    Country("Peru", "PE"),
    Country("Philippines", "PH"),
    Country("Pitcairn", "PN"),
    Country("Poland", "PL"),
    Country("Portugal", "PT"),
    Country("Puerto Rico", "PR"),
    Country("Qatar", "QA"),
    Country("Réunion", "RE"),
    Country("Romania", "RO"),
    Country("Russian Federation", "RU"),
    Country("Rwanda", "RW"),
    Country("Saint Helena, Ascension and Tristan da Cunha", "SH"),
    Country("Saint Kitts and Nevis", "KN"),
    Country("Saint Lucia", "LC"),
    Country("Saint Martin (French part)", "MF"),
    Country("Saint Pierre and Miquelon", "PM"),
    Country("Saint Vincent and the Grenadines", "VC"),
    Country("Samoa", "WS"),
    Country("San Marino", "SM"),
    Country("Sao Tome and Principe", "ST"),
    Country("Saudi Arabia", "SA"),
    Country("Senegal", "SN"),
    Country("Serbia", "RS"),
    Country("Serbia and Montenegro", "RS"),
    Country("Seychelles", "SC"),
    Country("Sierra Leone", "SL"),
    Country("Singapore", "SG"),
    Country("Sint Maarten (Dutch part)", "SX"),
    Country("Slovakia", "SK"),
    Country("Slovenia", "SI"),
    Country("Solomon Islands", "SB"),
    Country("Somalia", "SO"),
    Country("South Africa", "ZA"),
    Country("South Georgia and the South Sandwich Islands", "GS"),
    Country("South Sudan", "SS"),
    Country("Spain", "ES"),
    Country("Sri Lanka", "LK"),
    Country("Sudan", "SD"),
    Country("Suriname", "SR"),
    Country("Svalbard and Jan Mayen", "SJ"),
    Country("Swaziland", "SZ"),
    Country("Sweden", "SE"),
    Country("Switzerland", "CH"),
    Country("Syrian Arab Republic", "SY"),
    Country("Taiwan, Province of China", "TW"),
    Country("Tajikistan", "TJ"),
    Country("Tanzania, United Republic of", "TZ"),
    Country("Thailand", "TH"),
    Country("Timor-Leste", "TL"),
    Country("Togo", "TG"),
    Country("Tokelau", "TK"),
    Country("Tonga", "TO"),
    Country("Trinidad and Tobago", "TT"),
    Country("Tunisia", "TN"),
    Country("Turkey", "TR"),
    Country("Turkmenistan", "TM"),
    Country("Turks and Caicos Islands", "TC"),
    Country("Tuvalu", "TV"),
    Country("Uganda", "UG"),
    Country("Ukraine", "UA"),
    Country("United Arab Emirates", "AE"),
    Country("United Kingdom", "GB"),
    Country("United Nations", "UN"),
    Country("United States", "US"),
    Country("United States Minor Outlying Islands", "UM"),
    Country("Uruguay", "UY"),
    Country("Uzbekistan", "UZ"),
    Country("Vanuatu", "VU"),
    Country("Venezuela, Bolivarian Republic of", "VE"),
    Country("Viet Nam", "VN"),
    Country("Virgin Islands, British", "VG"),
    Country("Virgin Islands, U.S.", "VI"),
    Country("Wallis and Futuna", "WF"),
    Country("Western Sahara", "EH"),
    Country("Yemen", "YE"),
    Country("Zambia", "ZM"),
    Country("Zimbabwe", "ZW")
  )
}
